### ISSUE TITLE
Thread safe issue with visual_effect_generator

### ISSUE THREAD

**Issue by prickly-u** [lacmus-foundation/lacmus#108]
**Bug description**
The visual_effect_generator, as all python generators, is not thread-safe. That can cause an exception when using several worker threads, especially within single process.

**How to reproduce**
Enter the lacmus directory and run train.py with --workers > 1 but without --multiprocessing:

`keras_retinanet/bin/train.py --backbone mobilenet_v3_small --no-snapshots --batch-size 8  --max-queue-size=10 --workers=8 --epoch 1 --steps 200 pascal ../../../data/ful`   

**Actual result**
On one or another training step the process stops with an exception "ValueError: generator already executing"

**Callstack:**
Traceback (most recent call last):
  File "keras_retinanet/bin/train.py", line 546, in <module>
    main()
  File "keras_retinanet/bin/train.py", line 541, in main
    initial_epoch=args.initial_epoch
  File "/home/jupyter-kseniia/.local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/jupyter-kseniia/.local/lib/python3.7/site-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/jupyter-kseniia/.local/lib/python3.7/site-packages/keras/engine/training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "/home/jupyter-kseniia/.local/lib/python3.7/site-packages/keras/utils/data_utils.py", line 625, in get
    six.reraise(*sys.exc_info())
  File "/home/jupyter-kseniia/.conda/envs/lacmus-k/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/home/jupyter-kseniia/.local/lib/python3.7/site-packages/keras/utils/data_utils.py", line 610, in get
    inputs = future.get(timeout=30)
  File "/home/jupyter-kseniia/.conda/envs/lacmus-k/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/jupyter-kseniia/.conda/envs/lacmus-k/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/jupyter-kseniia/.local/lib/python3.7/site-packages/keras/utils/data_utils.py", line 406, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 375, in __getitem__
    inputs, targets = self.compute_input_output(group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 347, in compute_input_output
    image_group, annotations_group = self.random_visual_effect_group(image_group, annotations_group)
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 212, in random_visual_effect_group
    image_group[index], annotations_group[index]
  File "keras_retinanet/bin/../../keras_retinanet/preprocessing/generator.py", line 195, in random_visual_effect_group_entry
    visual_effect = next(self.visual_effect_generator)
ValueError: generator already executing
terminate called without an active exception
terminate called recursively
Aborted (core dumped)

**Comment by gosha20777** [comment]
https://github.com/lacmus-foundation/lacmus/pull/113#pullrequestreview-367293042

look at here
