### ISSUE TITLE
Bug: System.NullReferenceException throws while loading file

### ISSUE THREAD

**Issue by Denaizer** [lacmus-foundation/lacmus#71]
Version - 0.3.2
OS - Linux/Windows

На последнем и предпоследнем релизе есть плавающий глюк, систематику еще не выявил. При попытке загрузить с жесткого диска файлы программа падает с таким сообщением:
```
 Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at RescuerLaApp.Models.Frame.<>c__DisplayClass38_0.<Load>b__0(Object o)
   in /home/user/files/projects/lacmus/RescuerLaApp/Models/Frame.cs:line 77
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```
От количества файлов это не зависит, битых файлов нет.

**Comment by gosha20777** [comment]
The issue closed due to the transition of the repository to https://github.com/lacmus-foundation/lacmus-desctop-app/
